export const copy = {
  id: {
    lang: 'id',
    nav: { features: 'Fitur', how: 'Cara Kerja', support: 'Bantuan', menu: 'Buka menu' },
    home: {
      eyebrow: 'Untuk orang tua dan anak',
      title: 'Lebih dekat dengan orang tua, setiap hari.',
      intro: 'Hubungkan orang tua dan anak untuk mengatur pengingat kesehatan dan tetap terhubung melalui panggilan video.',
      soon: 'Segera hadir di App Store',
      howCta: 'Lihat Cara Kerja',
      screenAlt: 'Screenshot aplikasi Healder',
      screenPending: 'Screenshot aplikasi asli akan ditampilkan di sini.',
      screenNote: 'Aset final belum terlampir',
      featureKicker: 'Fitur utama',
      featureTitle: 'Dukungan sehari-hari, dalam satu tempat.',
      features: [
        ['Koneksi Orang Tua–Anak', 'Hubungkan profil orang tua dan anak menggunakan kode OTP.'],
        ['Pengingat Kesehatan', 'Anak membantu membuat pengingat kesehatan dan rutinitas untuk orang tua.'],
        ['Panggilan Video', 'Orang tua dapat menghubungi anak melalui panggilan video saat membutuhkan bantuan.'],
      ],
      howKicker: 'Cara kerja',
      howTitle: 'Mulai terhubung dalam tiga langkah.',
      steps: [
        'Buka Healder di perangkat orang tua dan anak.',
        'Hubungkan profil menggunakan kode OTP.',
        'Anak membuat pengingat; orang tua menerima pengingat dan dapat memulai panggilan video.',
      ],
    },
    support: {
      title: 'Bantuan Healder',
      intro: 'Butuh bantuan menggunakan Healder? Hubungi kami melalui email.',
      emailLabel: 'Email bantuan',
      button: 'Kirim Email',
      detailsTitle: 'Agar kami dapat membantu lebih cepat',
      detailsIntro: 'Sertakan informasi berikut di email Anda:',
      details: ['Model perangkat', 'Versi iOS', 'Versi aplikasi Healder', 'Deskripsi masalah'],
      screenshot: 'Screenshot bersifat opsional. Samarkan informasi pribadi dan kesehatan sebelum melampirkannya.',
      emergency: 'Untuk kondisi darurat, hubungi layanan darurat setempat. Jangan menunggu balasan email support.',
    },
    legal: {
      draft: 'Draf internal — belum untuk dipublikasikan',
      updated: 'Status: menunggu konfirmasi pemilik aplikasi',
      privacyTitle: 'Kebijakan Privasi Healder',
      privacyIntro: 'Draf ini memisahkan informasi produk yang sudah dikonfirmasi dari praktik data yang masih perlu dijelaskan oleh pemilik aplikasi.',
      privacySections: [
        ['Tentang Healder', ['Healder menghubungkan profil orang tua dan anak untuk membantu rutinitas, pengingat kesehatan, dan komunikasi melalui panggilan video.', 'Healder bukan layanan medis dan bukan pengganti layanan darurat atau nasihat medis profesional.']],
        ['Email bantuan', ['Jika Anda menghubungi ivanyuantama.work@gmail.com, informasi yang Anda kirimkan melalui email akan digunakan untuk menanggapi permintaan bantuan Anda.', 'Jika Anda melampirkan screenshot, samarkan informasi pribadi dan kesehatan yang tidak diperlukan.']],
        ['Praktik data yang belum dapat difinalkan', ['Kebijakan final perlu menjelaskan data yang dikumpulkan oleh aplikasi, tujuan penggunaannya, tempat dan lama penyimpanan, pihak yang dapat mengaksesnya, penyedia layanan yang terlibat, serta pilihan pengguna untuk mengakses atau menghapus data.', 'Draf ini tidak membuat asumsi mengenai enkripsi, rekaman panggilan, analitik, retensi, vendor, atau mekanisme penghapusan data.']],
      ],
      privacyQuestions: 'Informasi yang dibutuhkan sebelum publikasi',
      privacyItems: [
        'Nama lengkap pemilik atau badan hukum yang bertanggung jawab atas Healder dan alamat kontaknya.',
        'Jenis data yang dikumpulkan untuk profil, koneksi OTP, pengingat, dan panggilan video.',
        'Lokasi penyimpanan data, masa retensi, serta proses akses, koreksi, dan penghapusan data.',
        'Nama vendor atau penyedia layanan yang menerima atau memproses data pengguna.',
        'Apakah panggilan video direkam atau hanya diteruskan secara langsung.',
        'Negara atau wilayah sasaran dan ketentuan usia atau persetujuan yang berlaku.',
      ],
      termsTitle: 'Ketentuan Penggunaan Healder',
      termsIntro: 'Draf ini mencakup ruang lingkup layanan yang sudah dikonfirmasi dan menandai ketentuan yang memerlukan keputusan pemilik aplikasi.',
      termsSections: [
        ['Layanan Healder', ['Healder membantu orang tua dan anak menghubungkan profil menggunakan kode OTP, membuat dan menerima pengingat kesehatan atau rutinitas, serta memulai panggilan video.', 'Fitur tersebut ditujukan untuk dukungan sehari-hari dalam hubungan keluarga.']],
        ['Penggunaan yang bertanggung jawab', ['Gunakan Healder hanya dengan persetujuan anggota keluarga yang terhubung. Pastikan informasi pengingat yang dimasukkan sesuai dengan kebutuhan keluarga Anda.', 'Jangan menggunakan Healder untuk melanggar hukum, mengganggu layanan, atau mengakses profil orang lain tanpa izin.']],
        ['Batas layanan', ['Healder bukan layanan tanggap darurat atau layanan medis. Jangan mengandalkan Healder untuk kondisi yang memerlukan bantuan darurat atau nasihat medis profesional.', 'Ketersediaan dan keandalan fitur panggilan video dapat bergantung pada perangkat dan koneksi internet.']],
        ['Ketentuan yang belum dapat difinalkan', ['Ketentuan final masih memerlukan identitas penyedia layanan, aturan akun dan penghentian akses, hak kekayaan intelektual, batas tanggung jawab yang sesuai hukum, hukum yang berlaku, dan mekanisme perubahan ketentuan.', 'Draf ini tidak menetapkan umur minimum atau wilayah hukum tanpa konfirmasi.']],
      ],
      termsQuestions: 'Keputusan yang dibutuhkan sebelum publikasi',
      termsItems: [
        'Identitas hukum dan alamat penyedia Healder.',
        'Negara atau wilayah tempat aplikasi ditawarkan dan hukum yang berlaku.',
        'Ketentuan usia minimum dan persetujuan untuk menggunakan layanan.',
        'Aturan penghentian akun, perubahan layanan, serta pemberitahuan perubahan ketentuan.',
        'Ketentuan hak kekayaan intelektual dan batas tanggung jawab yang telah ditinjau secara hukum.',
        'Tanggal efektif untuk versi final ketentuan.',
      ],
    },
    footer: {
      support: 'Bantuan', privacy: 'Kebijakan Privasi', terms: 'Ketentuan Penggunaan',
      note: 'Healder bukan pengganti layanan darurat atau nasihat medis profesional.',
      rights: 'Healder. Seluruh hak dilindungi.',
    },
  },
  en: {
    lang: 'en',
    nav: { features: 'Features', how: 'How It Works', support: 'Support', menu: 'Open menu' },
    home: {
      eyebrow: 'For parents and their children',
      title: 'Stay closer to your parents, every day.',
      intro: 'Connect parents and their children to manage health reminders and stay in touch through video calls.',
      soon: 'Coming soon to the App Store',
      howCta: 'See How It Works',
      screenAlt: 'Healder app screenshot',
      screenPending: 'The original app screenshot will appear here.',
      screenNote: 'Final asset not attached yet',
      featureKicker: 'Core features',
      featureTitle: 'Everyday support, all in one place.',
      features: [
        ['Parent–Child Connection', 'Connect parent and child profiles using an OTP code.'],
        ['Health Reminders', 'Children can help create health and routine reminders for their parents.'],
        ['Video Calls', 'Parents can call their children by video when they need help.'],
      ],
      howKicker: 'How it works',
      howTitle: 'Get connected in three steps.',
      steps: [
        'Open Healder on the parent’s and child’s devices.',
        'Connect the profiles using an OTP code.',
        'The child creates reminders; the parent receives them and can start a video call.',
      ],
    },
    support: {
      title: 'Healder Support',
      intro: 'Need help using Healder? Contact us by email.',
      emailLabel: 'Support email',
      button: 'Send Email',
      detailsTitle: 'Help us assist you faster',
      detailsIntro: 'Please include the following in your email:',
      details: ['Device model', 'iOS version', 'Healder app version', 'A description of the issue'],
      screenshot: 'A screenshot is optional. Please hide personal and health information before attaching it.',
      emergency: 'In an emergency, contact your local emergency services. Do not wait for a support email response.',
    },
    legal: {
      draft: 'Internal draft — not ready for publication',
      updated: 'Status: awaiting confirmation from the app owner',
      privacyTitle: 'Healder Privacy Policy',
      privacyIntro: 'This draft separates confirmed product information from data practices that the app owner still needs to specify.',
      privacySections: [
        ['About Healder', ['Healder connects parent and child profiles to support routines, health reminders, and communication through video calls.', 'Healder is not a medical service and is not a replacement for emergency services or professional medical advice.']],
        ['Support email', ['If you contact ivanyuantama.work@gmail.com, the information you send by email will be used to respond to your support request.', 'If you attach a screenshot, hide any personal or health information that is not needed.']],
        ['Data practices that are not yet final', ['The final policy needs to explain what data the app collects, why it is used, where and how long it is stored, who can access it, which service providers are involved, and how users can access or delete their data.', 'This draft makes no assumptions about encryption, call recording, analytics, retention, vendors, or deletion methods.']],
      ],
      privacyQuestions: 'Information needed before publication',
      privacyItems: [
        'The full name of the person or legal entity responsible for Healder and its contact address.',
        'The data collected for profiles, OTP connections, reminders, and video calls.',
        'Where data is stored, how long it is retained, and the process for access, correction, and deletion.',
        'The vendors or service providers that receive or process user data.',
        'Whether video calls are recorded or only transmitted live.',
        'Target countries or regions and any applicable age or consent requirements.',
      ],
      termsTitle: 'Healder Terms of Use',
      termsIntro: 'This draft covers the confirmed service scope and identifies terms that still require decisions from the app owner.',
      termsSections: [
        ['The Healder service', ['Healder helps parents and their children connect profiles using an OTP code, create and receive health or routine reminders, and start video calls.', 'These features are intended for everyday support within a family relationship.']],
        ['Responsible use', ['Use Healder only with the agreement of the connected family member. Make sure reminder information reflects your family’s needs.', 'Do not use Healder to break the law, disrupt the service, or access another person’s profile without permission.']],
        ['Service limits', ['Healder is not an emergency response or medical service. Do not rely on Healder for situations that require emergency help or professional medical advice.', 'The availability and reliability of video calls may depend on the device and internet connection.']],
        ['Terms that are not yet final', ['The final terms still need the service provider’s identity, account and termination rules, intellectual property terms, legally appropriate limits of liability, governing law, and a process for changing these terms.', 'This draft does not set a minimum age or jurisdiction without confirmation.']],
      ],
      termsQuestions: 'Decisions needed before publication',
      termsItems: [
        'The legal identity and address of the Healder service provider.',
        'The countries or regions where the app is offered and the governing law.',
        'Minimum-age and consent requirements for using the service.',
        'Rules for account termination, service changes, and notice of changes to these terms.',
        'Intellectual-property terms and limits of liability reviewed for the applicable law.',
        'The effective date for the final terms.',
      ],
    },
    footer: {
      support: 'Support', privacy: 'Privacy Policy', terms: 'Terms of Use',
      note: 'Healder is not a replacement for emergency services or professional medical advice.',
      rights: 'Healder. All rights reserved.',
    },
  },
}
